[package]
name = "slang"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
slang-sys = { path = "slang-sys" }
thiserror = "2.0"

[workspace]
members = [
	"slang-sys"
]
